---
title: "Installation / Usage"
title-block-banner: true
---

After clicking the "Download CSS" button on any theme's page, your browser likely loads the `.css` file instead of downloading it. You can save the `.css` file locally using `Ctrl + S`.

### Marp for VS Code Extension

1. Open Settings in VSCode (`Ctrl + ,`)
2. Search for "Marp: Themes" or "markdown.marp.themes"
3. After downloading the theme, add its local `path/to/the/file.css` in the settings. Alternatively, add a trustworthy remote path to the CSS file
   - *Links*: please, consider forking the repository and hosting the CSS files using, for example, GitHub Pages ([related Stack Overflow discussion](https://stackoverflow.com/a/52921967)) instead of linking to the raw file on GitHub (refer to [GitHub's blogpost](https://github.blog/2013-04-24-heads-up-nosniff-header-support-coming-to-chrome-and-firefox/) for more info)

4. Enable the theme in the front-matter of the Markdown document, i.e., write the following at the very beginning of the Markdown document:

```
---
marp: true
theme: theme_name
---
```

For additional settings (such as `size` or `paginate`), follow the [official documentation](https://github.com/marp-team/marp/blob/main/website/docs/guide/directives.md).

### Marp CLI

1. Put the `.css` theme file in the directory of your Markdown document
2. Use the `--theme` parameter during the export and specify the path to the `.css` file
   - e.g.: 
   
```
marp --theme ./assets/theme_name.css document.md -o document.pdf
```
